services:
  - type: web
    name: trail-backend
    env: python3
    script:
      - apt-get update
      - apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-hin
      - pip install -r requirements.txt
      - gunicorn index:app
